# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CmdLine@2
  inputs:
    script: 'make build'
- task: CmdLine@2
  inputs:
    script: 'make up'
- script: |
    docker exec django /bin/sh -c "python manage.py test --testrunner xmlrunner.extra.djangotestrunner.XMLTestRunner --no-input"
  displayName: 'Run tests'
- task: PublishTestResults@2
  inputs:
    testResultsFiles: "**/TEST-*.xml"
    testRunTitle: 'Unit Tests'
  condition: succeededOrFailed()
- task: CmdLine@2
  inputs:
    script: 'make stop'